In [1]:
import os
import sys
import pandas as pd
sys.path.append('..')
from vector_service.vector_db import *
from chatbot_app.chatbot import *
from src.utils.paths import get_project_path

/Users/vinavolo/Public/Project/SciNanoAI/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from chatbot_app.llm.ollama_client import OllamaChatClient

In [ ]:
model = OllamaChatClient(
            model_name="gpt-oss:latest",
            base_url="http://ollama.lab:11434/api/chat"
        )

model.generate(messages="asdasd")

HTTPError: 404 Client Error: Not Found for url: http://ollama.lab:11434/api/chat/completions

In [14]:
dd = pd.read_excel("/Users/vinavolo/Documents/Project/SciNanoAI/notebooks/30_val_DEL_one.xlsx").drop(columns=["Unnamed: 0"])

dj = pd.read_excel("/Users/vinavolo/Documents/Project/SciNanoAI/notebooks/30_val_DEL_one_2.xlsx").drop(columns=["Unnamed: 0"])

In [15]:
dj

,Запрос,Модельный ответ,Статья,openai/gpt-4,openai/gpt-4o-mini,openai/gpt-4o-2024-11-20,meta-llama/llama-3.1-405b-instruct,openai/gpt-5-chat,openai/gpt-oss-120b,google/gemini-2.5-flash-lite
0,какие конкретные геометрии 3D-каркасов были из...,с использованием материала SZ2080 были напечат...,2_6_Полина_Металл_10.1088.pdf,"Согласно представленной информации, материал S...",С использованием материала SZ2080 были изготов...,"На основании предоставленной информации, матер...",Изготовление 3D-каркасов с использованием мате...,"Из приведённых данных можно заключить, что при...",С материалом SZ2080 в рамках предклинического ...,С использованием материала SZ2080 были изготов...
1,какие материалы использовали для изготовления ...,для изготовления каркасов использовали два раз...,1_12_sbytov.pdf,Структурированный каркас для роста клеточных к...,Для изготовления структурированного каркаса (и...,Для изготовления структурированных каркасов дл...,Для изготовления структурированного каркаса дл...,Для изготовления структурированных каркасов (с...,**Ответ:** \n\nДля создания **структурированн...,## Материалы для изготовления структурированны...
2,какую архитектуру глубокого обучения можно исп...,модель многозадачного глубокого обучения. Моде...,2020_Multitask deep-learning-based design of c...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для решения задачи моделирования и оптимизации...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...
3,"как различная глубина наноям (80, 220 и 333 нм...","различная глубина наноям (80, 220 и 333 нм) ок...",8_5_Настя_j.biomaterials.2011.09.073.pdf,"Исследования показывают, что глубина наноям мо...","Различная глубина наноям, таких как 80, 220 и ...","Различная глубина наноям (80, 220 и 333 нм) ок...",Различная глубина наноям оказывает существенно...,"Исследования показали, что глубина наноям игра...",Различная глубина наноям оказывает существенно...,"Исследования показывают, что глубина наноям ок..."
4,как изменения в механических условиях могут по...,"клетки используют механосенсорные пути, активи...",10_4_Полина_j.bpj.2012.07.023.pdf,Изменения в механических условиях могут оказыв...,Изменения в механических условиях окружающей с...,Изменения в механических условиях окружающей с...,Изменения в механических условиях могут сущест...,Изменения в механических условиях клеточного м...,Механические условия окружающей среды оказываю...,Механические условия окружающей среды играют к...
5,"какие факторы, помимо топографии, могут влиять...",на поведение остеопогениторных клеток помимо т...,9_3_Полина_Nanopit-induced_osteoprogenitor_cel...,"Остеопогениторные клетки, или клетки, способны...","Остеопогениторные клетки, или предшественники ...",Остеопогениторные клетки (предшественники осте...,"Поведение остеопогениторных клеток, которые яв...","Помимо топографии поверхности, на поведение ос...",**Ответ:** \n\nОстеопогениторные (остеопробле...,"## Факторы, влияющие на поведение остеопогенит..."
6,какие механизмы клеточной адгезии активируются...,при взаимодействии с наноструктурированными по...,8_6_Настя_j.colsurfb.2014.03.019.pdf,"Механизмы клеточной адгезии, активирующиеся пр...",При взаимодействии клеток с наноструктурирован...,При взаимодействии клеток с наноструктурирован...,"Механизмы клеточной адгезии, активируемые при ...",При взаимодействии клеток с наноструктурирован...,Взаимодействие клеток с наноструктурированными...,Взаимодействие клеток с наноструктурированными...
7,Какое влияние нанопаттерны и микропаттерны мог...,Нанопаттерны могут увеличивать площадь поверхн...,8_2_Настя_j.actbio.2009.03.027.pdf,Нанопаттерны и микропаттерны могут оказывать з...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны могут оказывать з...,Нанопаттерны и микропаттерны оказывают выражен...,Нанопаттерны и микропаттерны оказывают существ...,Нанопаттерны и микропаттерны оказывают существ...
8,Какие ограничения могут возникнуть в процессе ...,В процессе автоматизации обработки текстов и и...,2020_Nanomaterial Synthesis Insights from Mach...,Автоматизация обработки текстов и изображений ...,Автоматизация обработки текстов и изображений ...,Автоматизация обработки текстов и изображений ...,При автоматизации обработки текстов и изображе...,Автоматизация обработки текстов и изображений ...,Автоматизация извлечения и структурирования ин...,Автоматизация обработки текстов и изображений ...
9,Как динамическое микропаттернирование на нано...,"Клетки, находясь на подобных наноструктурах, ...",kweon-et-al-2016-dynamic-micropatterning-\nof-...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование клеток на на...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...
10,Оказывает ли влияние фотополимер SU-8 на биосо...,SU-8 может иметь определённые ограничения по б...,5_1_4_Полина_2015_3D Printed Microtransporters...,"Фотополимер SU-8, являющийся эпоксидной негати...","Фотополимер SU-8, являющийся эпоксидным негати...","Фотополимер SU-8, являющийся эпоксидным негати...",Фотополимер SU-8 является широко используемым ...,"Фотополимер SU-8, являющийся эпоксидным негати...",Фотополимер SU‑8 традиционно рассматривается к...,"Фотополимер SU-8, широко используемый в микрос..."
11,Какие типы наноструктур можно получить с испол...,С использованием технологии лазерной обработки...,5_2_4_Полина.pdf,Технология двухфотонной полимеризации негативн...,С использованием технологии двухфотонной полим...,Технология двухфотонной полимеризации (Two-Pho...,Технология двухфотонной полимеризации негативн...,При использовании технологии двухфотонной поли...,Технология двухфотонной полимеризации (Two‑Pho...,Технология двухфотонной полимеризации (TPP) пр...
12,Какие типы материалов можно использовать в дву...,"Синтетические и природные полимеры, которые мо...",РЕВ_6_3_Полина_Adv Funct Materials - 2013 - To...,Для обеспечения высокой степени биосовместимос...,В двухфотонной полимеризации (2ПП) для создани...,Двухфотонная полимеризация (ДФП) представляет ...,Для обеспечения высокой степени биосовместимос...,Для обеспечения высокой степени биосовместимос...,Для обеспечения высокой степени биосовместимос...,Для обеспечения высокой степени биосовместимос...
13,Как фотолитография влияет на клеточную адгезию...,Фотолитография позволяет создавать контролируе...,12_3_Полина_j.biomaterials.2011.07.035 (1).pdf,"Фотолитография - это процесс, который использу...","Фотолитография, как метод создания микро- и на...","Фотолитография, как метод создания микро- и на...","Фотолитография, как метод создания микро- и на...",Прямое применение фотолитографии в биомедицинс...,"Фотолитография, будучи самым точным и масштаби...","Фотолитография, являясь эталонной технологией ..."
14,Как микростолбики (micropillars) влияют на кле...,Микростолбики (micropillars) значительно влияю...,12_4_Полина_j.biomaterials.2013.01.018.pdf,Микростолбики (micropillars) могут оказывать в...,Микростолбики (micropillars) представляют собо...,Микростолбики (micropillars) оказывают значите...,Микростолбики (micropillars) оказывают влияние...,Влияние микростолбиков (micropillars) на морфо...,Микростолбики (micropillars) представляют собо...,Микростолбики (micropillars) оказывают значите...
15,Какие конкретные геометрии 3Д-каркасов были из...,С использованием материала SZ2080 были напечат...,2_6_Полина_Металл_10.1088.pdf,Материал SZ2080 был использован для изготовлен...,"Согласно предоставленной информации, материал ...",На основании предоставленной информации можно ...,Изготовление 3Д-каркасов с использованием мате...,На сегодняшний день можно достаточно уверенно ...,С материалом SZ2080 в рамках предклинических и...,С использованием материала SZ2080 были изготов...
16,"Какой размер структур можно получить, использу...",С использованием фотополимера Ormocomp и техно...,4_6_Полина_2015_cell-stimulation.pdf,Используя коммерчески доступный фотополимер Or...,Используя коммерчески доступный фотополимер Or...,"Коммерчески доступный фотополимер Ormocomp, пр...",Используя коммерчески доступный фотополимер Or...,"Коммерчески доступный фотополимер Ormocomp®, р...",Используемый в микрофабрикации фотополимер Orm...,"Коммерчески доступный фотополимер OrmoComp®, п..."
17,Какие структуры можно получить двухфотонной по...,С использованием фотополимеров IP-Dip и IP-Q в...,5_1_1_Полина.pdf,Двухфотонная полимеризация (TPP) с использован...,Двухфотонная полимеризация (TPP) представляет ...,"Двухфотонная полимеризация (TPP, Two-Photon Po...","Двухфотонная полимеризация (TPP) - это метод, ...",Двухфотонная полимеризация (Two-Photon Polymer...,Двухфотонная полимеризация (TPP) в сочетании с...,Двухфотонная полимеризация (TPP) является мощн...
18,Какие преимущества предоставляет использование...,Полиуретановый акрилат предлагает высокую UV-к...,5_2_1_Полина.pdf,Полиуретановый акрилат в сравнении с другими т...,Использование полиуретанового акрилата в 3D пе...,Полиуретановые акрилаты (ПУА) представляют соб...,Использование полиуретанового акрилата в 3D пе...,Использование полиуретанового акрилата (PUA) в...,Использование полиуретанового акрилата в фотоп...,Полиуретановые акрилаты демонстрируют ряд преи...
19,Как фотопрезистор PI184 влияет на процесс поли...,"Фотопрезистор PI184 инициирует полимеризацию, ...",5_2_1_Полина.pdf,"Похоже, что вопрос содержит некоторую путаницу...",Фотопрезистор PI184 — это полупроводниковый эл...,"Фотопрезистор PI184, как и другие фотопрезисто...",Фотопрезистор PI184 представляет собой светочу...,Я немного уточню: судя по формулировке вопроса...,**Ответ:** \n\nФотопрезистор **PI184** (часто...,## Влияние фотопрезистора PI184 на процесс пол...
20,Каковы эффекты наноструктурированных поверхнос...,Оказывают заметный эффект в снижении клеточной...,4_12_sbytov.pdf,Наноструктурированные поверхности оказывают зн...,Наноструктурированные поверхности оказывают зн...,Наноструктурированные поверхности оказывают зн...,Эффекты наноструктурированных поверхностей на ...,Наноструктурированные поверхности оказывают вы...,Наноструктурированные поверхности оказывают мн...,Наноструктурированные поверхности оказывают зн...
21,Каким образом наноструктуры влияют на дифферен...,Нанорешетки (nanogratings) с шириной полосок 3...,1-s2.0-S0014482707000924-main.pdf,Наноструктуры могут влиять на дифференцировку ...,Наноструктуры оказывают значительное влияние н...,Наноструктуры оказывают значительное влияние н...,Наноструктуры могут оказывать значительное вли...,Наноструктуры оказывают на мезенхимальные ство...,Наноструктурированные поверхности оказывают мн...,Наноструктуры оказывают многогранное влияние н...
22,Какая роль TiO2 нанотрубок в остеогенной диффе...,TiO2 нанотрубки способствуют остеогенной диффе...,1-s2.0-S0142961214011582-main.pdf,TiO2 нанотрубки играют важную роль в остеогенн...,TiO2 нанотрубки играют значительную роль в ост...,TiO2 нанотрубки играют значительную роль в ост...,Роль TiO2 нанотрубок в остеогенной дифференцир...,"Наноструктурированные поверхности, в частности...",TiO₂ нанотрубки (TiO₂ nanotubes) выступают мощ...,Нанотрубки из диоксида титана (TiO2 nanotubes)...
23,Как диаметр наноигл (nanoneedles) влияет на мо...,Уменьшение диаметра наноигл (nanoneedles) увел...,seong-et-al-2020-size-tunable-nanoneedle-\narr...,Диаметр наноигл может оказывать влияние на мор...,Диаметр наноигл (nanoneedles) оказывает значит...,Диаметр наноигл (nanoneedles) оказывает значит...,Размер наноигл (nanoneedles) может существенно...,Диаметр наноигл (nanoneedles) является одним и...,Диаметр наноигл (nanoneedles) является одним и...,Диаметр наноигл (nanoneedles) оказывает сущест...
24,Как адгезия клеток зависит от форм и размеров ...,Адгезия клеток зависит от форм и размеров нано...,8_2_Настя_j.actbio.2009.03.027.pdf,Адгезия клеток на микро- и нанотекстурированны...,Адгезия клеток на микро- и нанотекстурированны...,Адгезия клеток на наноструктурированных поверх...,Адгезия клеток на поверхностях с наноразмерным...,Адгезия клеток на нанотекстурированных поверхн...,Адгезия клеток к нанотекстурированным субстрат...,Адгезия клеток к поверхностям с нанопаттернами...
25,Как с помощью нейросетей можно оптимизировать...,Чтобы оптимизировать размер радиуса нанострукт...,2019_Optimisation of colour generation from di...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с использован...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с использован...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с помощью ней...
26,Какое влияние нанопаттерны и микропаттерны мог...,Нанопаттерны могут способствовать увеличению п...,8_2_Настя_j.actbio.2009.03.027.pdf,Нанопаттерны и микропаттерны могут оказывать з...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны могут оказывать з...,Наноповерхности и микропаттерированные подложк...,Нанопаттерны и микропаттерны способны существе...,Нанопаттерны и микропаттерны оказывают значите...

In [10]:
df = pd.read_excel("/Users/vinavolo/Documents/Project/SciNanoAI/notebooks/30_val_REW.xlsx")

In [6]:
# for mod in ["openai/gpt-4", "openai/gpt-4o-mini", "openai/gpt-4o-2024-11-20", "meta-llama/llama-3.1-405b-instruct", "YandexGPT4", "openai/gpt-5-chat", "openai/gpt-oss-120b","google/gemini-2.5-flash-lite"]:

for mod in ["openai/gpt-5-chat", "openai/gpt-oss-120b","google/gemini-2.5-flash-lite"]:

    ans = []

    for i in range(len(df)):
        
        chatbot = ChatBot(llm_model=mod)
        
        
        vec = VectorDatabase(
            db_path="/Users/vinavolo/Documents/Project/SciNanoAI/db/intfloat_multilingual-e5-large/",
            model_name="intfloat/multilingual-e5-large"
        )
        
        vec.delete_document_by_name(df.Статья.iloc[i])
        
        print(i)
        resp = chatbot.generate_response(df.Запрос.iloc[i], df.Статья.iloc[i])
        
        ans.append(resp)

    df[mod] = ans

    df.to_excel('30_val_DEL_one_3.xlsx')

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

0
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

1
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

2
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

3
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

4
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

5
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

6
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

7
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

8
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

9
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

10
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

11
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

12
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

13
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

14
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

15
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

16
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

17
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

18
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

19
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

20
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

21
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

22
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

23
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

24
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

25
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

26
<Response [200]>
Используется модель: openai/gpt-5-chat

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

0
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

1
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

2
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

3
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

4
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

5
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

6
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

7
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

8
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

9
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

10
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

11
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

12
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

13
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

14
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

15
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

16
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

17
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

18
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

19
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

20
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

21
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

22
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

23
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

24
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

25
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

26
<Response [200]>
Используется модель: openai/gpt-oss-120b

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

0
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

1
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

2
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

3
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

4
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

5
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

6
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

7
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

8
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

9
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

10
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

11
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

12
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

13
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

14
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

15
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

16
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

17
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

18
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

19
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

20
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

21
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

22
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

23
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

24
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

25
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

26
<Response [200]>
Используется модель: google/gemini-2.5-flash-lite

In [5]:
df

,Запрос,Модельный ответ,openai/gpt-4o-mini,openai/gpt-4o-2024-11-20,YandexGPT4,GigaChat-Pro,meta-llama/llama-3.1-405b-instruct,openai/gpt-4-turbo
0,какие конкретные геометрии 3D-каркасов были из...,с использованием материала SZ2080 были напечат...,С использованием материала SZ2080 были изготов...,"Согласно предоставленной информации, материал ...",В работе представлены результаты исследования ...,В ходе исследования был использован материал S...,"На основе предоставленной информации, материал...",Исследование материала SZ2080 для создания 3D-...
1,какие материалы использовали для изготовления ...,для изготовления каркасов использовали два раз...,"Для изготовления структурированного каркаса, п...","Для изготовления структурированных каркасов, п...","Для изготовления структурированного каркаса, к...","Для создания структурированных каркасов, спосо...",Для изготовления структурированного каркаса дл...,"Для изготовления структурированных каркасов, п..."
2,какую архитектуру глубокого обучения можно исп...,модель многозадачного глубокого обучения. Моде...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...,Для моделирования и оптимизации геометрических...
3,"как различная глубина наноям (80, 220 и 333 нм...","различная глубина наноям (80, 220 и 333 нм) ок...","Различная глубина наноям, таких как 80, 220 и ...","Различная глубина наноям (80, 220 и 333 нм) ок...","Согласно приведённому контексту, более мелкие ...",На основании представленной информации можно с...,"Различная глубина наноям (80, 220 и 333 нм) ок...","Исследования показывают, что глубина наноям ок..."
4,как изменения в механических условиях могут по...,"клетки используют механосенсорные пути, активи...",Изменения в механических условиях окружающей с...,Изменения в механических условиях оказывают зн...,"Механические условия, такие как напряжение и с...",Механические условия играют важную роль в регу...,Изменения в механических условиях могут оказыв...,Изменения в механических условиях окружающей с...
5,"какие факторы, помимо топографии, могут влиять...",на поведение остеопогениторных клеток помимо т...,"Помимо топографии, на поведение остеопогенитор...","Поведение остеопогениторных клеток, помимо вли...",На поведение остеопрогениторных клеток могут в...,Поведение остеопоэтинных клеток может зависеть...,"Помимо топографии, на поведение остеопогенитор...","Помимо топографии, на поведение остеопогенитор..."
6,какие механизмы клеточной адгезии активируются...,при взаимодействии с наноструктурированными по...,При взаимодействии с наноструктурированными по...,"Механизмы клеточной адгезии, активируемые при ...",Взаимодействие клеток с наноструктурированными...,При взаимодействии клеток с наноструктурирован...,При взаимодействии с наноструктурированными по...,Взаимодействие клеток с наноструктурированными...
7,Какое влияние нанопаттерны и микропаттерны мог...,Нанопаттерны могут увеличивать площадь поверхн...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны оказывают значите...,"В научной литературе отмечается, что нанопатте...",Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны могут оказывать з...,Нанопаттерны и микропаттерны оказывают значите...
8,Какие ограничения могут возникнуть в процессе ...,В процессе автоматизации обработки текстов и и...,Автоматизация обработки текстов и изображений ...,Автоматизация обработки текстов и изображений ...,В процессе автоматизации обработки текстов и и...,Процесс автоматизации обработки текстов и изоб...,При автоматизации обработки текстов и изображе...,Автоматизация обработки текстов и изображений ...
9,Как динамическое микропаттернирование на нано...,"Клетки, находясь на подобных наноструктурах, ...",Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...,В работе «Dynamic Micropatterning of Cells on ...,Динамическое микропаттернирование клеток на на...,Динамическое микропаттернирование на нанострук...,Динамическое микропаттернирование на нанострук...
10,Оказывает ли влияние фотополимер SU-8 на биосо...,SU-8 может иметь определённые ограничения по б...,"Фотополимер SU-8, представляющий собой эпоксид...","Фотополимер SU-8, широко используемый в микро-...",На основе анализа предоставленной информации м...,Фотополимер SU-8 широко используется в микрофл...,Фотополимер SU-8 является широко используемым ...,"Фотополимер SU-8, широко используемый в микроф..."
11,Какие типы наноструктур можно получить с испол...,С использованием технологии лазерной обработки...,Технология двухфотонной полимеризации (TPP) не...,Технология двухфотонной полимеризации (Two-Pho...,С использованием технологии двухфотонной полим...,Технология двухфотонной полимеризации (Two-Pho...,Технология двухфотонной полимеризации негативн...,Технология двухфотонной полимеризации (TPL) с ...
12,Какие типы материалов можно использовать в дву...,"Синтетические и природные полимеры, которые мо...",В двухфотонной полимеризации (TPP) для обеспеч...,Двухфотонная полимеризация (Two-Photon Polymer...,Для обеспечения высокой степени биосовместимос...,В двухфотонной полимеризации (2PP) для создани...,Для обеспечения высокой степени биосовместимос...,В последние годы технология двухфотонной полим...
13,Как фотолитография влияет на клеточную адгезию...,Фотолитография позволяет создавать контролируе...,"Фотолитография, как метод создания микрострукт...","Фотолитография, как метод создания микро- и на...",В предоставленных источниках нет прямого ответ...,"Фотолитография представляет собой технологию, ...",Фотолитография может оказывать влияние на клет...,"Фотолитография, как метод создания микро- и на..."
14,Как микростолбики (micropillars) влияют на кле...,Микростолбики (micropillars) значительно влияю...,Микростолбики (micropillars) представляют собо...,Микростолбики (micropillars) оказывают значите...,"Взаимодействие клеток с поверхностями, имеющим...",Микростолбики (micropillars) представляют собо...,Микростолбики (micropillars) могут оказывать в...,"Исследования последних десятилетий показывают,..."
15,Какие конкретные геометрии 3Д-каркасов были из...,С использованием материала SZ2080 были напечат...,С использованием материала SZ2080 были изготов...,"Материал SZ2080, представляющий собой гибридны...",В работе «Preclinical study of SZ2080 material...,В ходе исследования был использован материал S...,На основе предоставленной информации можно зак...,"Используя материал SZ2080, были созданы различ..."
16,"Какой размер структур можно получить, использу...",С использованием фотополимера Ormocomp и техно...,Используя коммерчески доступный фотополимер Or...,"Коммерчески доступный фотополимер Ormocomp, пр...",На основе предоставленной информации нельзя то...,Коммерчески доступный фотополимер OrmoComp® от...,Используя коммерчески доступный фотополимер Or...,"Используя фотополимер OrmoComp, который предос..."
17,Какие структуры можно получить двухфотонной по...,С использованием фотополимеров IP-Dip и IP-Q в...,Двухфотонная полимеризация (TPP) с использован...,Двухфотонная полимеризация (Two-Photon Polymer...,На основе предоставленной информации можно сде...,"Двухфотонная полимеризация (ДФП), используемая...","Используя фотополимеры IP-Dip и IP-Q, можно по...",Двухфотонная полимеризация (TPP) представляет ...
18,Какие преимущества предоставляет использование...,Полиуретановый акрилат предлагает высокую UV-к...,Использование полиуретанового акрилата в 3D пе...,Полиуретановые акрилаты (PUA) представляют соб...,В нашем исследовании успешно синтезирован поли...,Полиуретановый акрилат обладает рядом преимуще...,Использование полиуретанового акрилата в сравн...,Использование полиуретанового акрилата в техно...
19,Как фотопрезистор PI184 влияет на процесс поли...,"Фотопрезистор PI184 инициирует полимеризацию, ...",Фотопрезистор PI184 играет важную роль в проце...,"Фотопрезистор PI184, как и другие фотополимеры...",В предоставленном контексте нет информации о в...,Фотополимер PI184 является важным компонентом ...,Фотопрезистор PI184 является ключевым компонен...,"Фотопрезистор PI184, как и другие фотополимеры..."
20,Каковы эффекты наноструктурированных поверхнос...,Оказывают заметный эффект в снижении клеточной...,Наноструктурированные поверхности оказывают зн...,Наноструктурированные поверхности оказывают зн...,"В последние годы исследования показали, что на...",Наноструктурированные поверхности оказывают зн...,Эффекты наноструктурированных поверхностей на ...,Наноструктурированные поверхности оказывают зн...
21,Каким образом наноструктуры влияют на дифферен...,Нанорешетки (nanogratings) с шириной полосок 3...,Наноструктуры оказывают значительное влияние н...,Наноструктуры оказывают значительное влияние н...,"Вопрос о том, как наноструктуры влияют на дифф...",Наноструктуры оказывают значительное влияние н...,Наноструктуры могут оказывать значительное вли...,Наноструктуры оказывают значительное влияние н...
22,Какая роль TiO2 нанотрубок в остеогенной диффе...,TiO2 нанотрубки способствуют остеогенной диффе...,TiO2 нанотрубки играют важную роль в остеогенн...,Нанотрубки диоксида титана (TiO2) играют важну...,На основании предоставленной информации можно ...,**Роль TiO2 нанотрубок в остеогенной дифференц...,TiO2 нанотрубки играют значительную роль в ост...,TiO2 нанотубки играют значительную роль в осте...
23,Как диаметр наноигл (nanoneedles) влияет на мо...,Уменьшение диаметра наноигл (nanoneedles) увел...,Диаметр наноигл (nanoneedles) оказывает значит...,Диаметр наноигл (nanoneedles) оказывает значит...,В статье «Size-Tunable Nanoneedle Arrays for I...,"Наноразмерные структуры, такие как наноиглы, м...",Диаметр наноигл (nanoneedles) может оказывать ...,Диаметр наноигл (nanoneedles) оказывает значит...
24,Как адгезия клеток зависит от форм и размеров ...,Адгезия клеток зависит от форм и размеров нано...,Адгезия клеток на микро- и нанотекстурированны...,Адгезия клеток на наноструктурированных поверх...,Адгезия клеток на микро- и наноструктурированн...,Адгезия клеток к поверхностям с микро- и нанос...,Адгезия клеток на нанопаттернах зависит от раз...,Адгезия клеток к поверхностям с нанопаттернами...
25,Как с помощью нейросетей можно оптимизировать...,Чтобы оптимизировать размер радиуса нанострукт...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с использован...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с помощью ней...,Оптимизация радиуса наноструктур с помощью ней...
26,Какое влияние нанопаттерны и микропаттерны мог...,Нанопаттерны могут способствовать увеличению п...,Нанопаттерны и микропаттерны оказывают значите...,Нанопаттерны и микропаттерны оказывают значите...,Нано- и микропаттерны могут оказывать значител...,Нанопаттерны и микропаттерны могут существенно...,Нанопаттерны и микропаттерны могут оказывать з...,Нанопаттерны и микропаттерны оказывают значите...